// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgCreateDidDoc } from "./types/cheqd/did/v2/tx";
import { MsgUpdateDidDoc } from "./types/cheqd/did/v2/tx";
import { MsgDeactivateDidDoc } from "./types/cheqd/did/v2/tx";


export { MsgCreateDidDoc, MsgUpdateDidDoc, MsgDeactivateDidDoc };

type sendMsgCreateDidDocParams = {
  value: MsgCreateDidDoc,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateDidDocParams = {
  value: MsgUpdateDidDoc,
  fee?: StdFee,
  memo?: string
};

type sendMsgDeactivateDidDocParams = {
  value: MsgDeactivateDidDoc,
  fee?: StdFee,
  memo?: string
};


type msgCreateDidDocParams = {
  value: MsgCreateDidDoc,
};

type msgUpdateDidDocParams = {
  value: MsgUpdateDidDoc,
};

type msgDeactivateDidDocParams = {
  value: MsgDeactivateDidDoc,
};


export const registry = new Registry(msgTypes);

const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgCreateDidDoc({ value, fee, memo }: sendMsgCreateDidDocParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreateDidDoc: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCreateDidDoc({ value: MsgCreateDidDoc.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreateDidDoc: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateDidDoc({ value, fee, memo }: sendMsgUpdateDidDocParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateDidDoc: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgUpdateDidDoc({ value: MsgUpdateDidDoc.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateDidDoc: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgDeactivateDidDoc({ value, fee, memo }: sendMsgDeactivateDidDocParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgDeactivateDidDoc: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgDeactivateDidDoc({ value: MsgDeactivateDidDoc.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgDeactivateDidDoc: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgCreateDidDoc({ value }: msgCreateDidDocParams): EncodeObject {
			try {
				return { typeUrl: "/cheqd.did.v2.MsgCreateDidDoc", value: MsgCreateDidDoc.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreateDidDoc: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateDidDoc({ value }: msgUpdateDidDocParams): EncodeObject {
			try {
				return { typeUrl: "/cheqd.did.v2.MsgUpdateDidDoc", value: MsgUpdateDidDoc.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateDidDoc: Could not create message: ' + e.message)
			}
		},
		
		msgDeactivateDidDoc({ value }: msgDeactivateDidDocParams): EncodeObject {
			try {
				return { typeUrl: "/cheqd.did.v2.MsgDeactivateDidDoc", value: MsgDeactivateDidDoc.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgDeactivateDidDoc: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			CheqdDidV2: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;