name: "Build"
on:
  workflow_call:
defaults:
  run:
    shell: bash

env:
  BIN_NAME: canow-chain

jobs:
  build-binary:
    name: "Node binary"
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]
        include:
          - os: ubuntu-20.04
            goos: linux
          - os: macos-11
            goos: darwin
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod

      - name: Build application binary
        run: env VERSION="$( git describe --tags ${{ github.sha }})" CGO_ENABLED=1 GOOS=${{ matrix.goos }} GOARCH=amd64 make build

      - name: Store artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BIN_NAME }}-${{ matrix.goos }}
          path: build/${{ env.BIN_NAME }}

  build-docker:
    name: "Docker image"
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
          version: latest

      - name: Configure Docker image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=raw,value=build-latest
            type=sha,format=long

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64
          load: true
          target: runner
          tags: ${{ steps.meta.outputs.tags }}
          outputs: type=docker,dest=/tmp/canow-chain-build.tar
          cache-from: type=gha
          cache-to: type=gha,mode=min

      - name: Upload Docker build image
        uses: actions/upload-artifact@v3
        with:
          name: canow-chain-build.tar
          path: /tmp/canow-chain-build.tar
