name: "Workflow Dispatch"
on:
  pull_request:
    types:
      - opened
      - edited
      - closed
      - reopened
      - synchronize
  push:
    tags:
      - '*'
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:

  call-lint:
    name: "Lint"
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  call-build:
    name: "Build"
    uses: ./.github/workflows/build.yml
    secrets: inherit
  
  call-test:
    name: "Tests"
    needs: call-build
    uses: ./.github/workflows/test.yml
    secrets: inherit
